// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Binamicle",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Binamicle",
            targets: ["AppModule"],
            bundleIdentifier: "nl.joephinderink.Binamicle",
            teamIdentifier: "B492Q5WQL4",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "The app needs to access the camera in order to scan documents."),
                .microphone(purposeString: "The app needs to access to Speech Recognition in order to convert audio to text."),
                .speechRecognition(purposeString: "The app needs to access to Speech Recognition in order to convert audio to text.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)